apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: my-doc
  namespace: redisns
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  databaseSecretName: redb-my-doc
  memorySize: 1GB
  modulesList:
    - name: search
      version: 2.10.18
  persistence: snapshotEvery12Hour
  replication: true
  tlsMode: disabled
  type: redis
