apiVersion: batch/v1
kind: Job
metadata:
  name: guidellm-benchmark
  namespace: ml-benchmark
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: benchmark
        image: my.registry.io/guidellm/guidellm:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting GuideLLM benchmark..."
          guidellm benchmark \
            --endpoint http://vllm-service:8000 \
            --requests 5000 \
            --concurrency 8 \
            --output /results/output.json
        volumeMounts:
        - name: results
          mountPath: /results
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: benchmark-results-pvc
