apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-results-pvc
  namespace: ml-benchmark
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "mcp-pf-fs-storageclass"
  resources:
    requests:
      storage: 20Gi
