---
# 2️⃣ App of Apps ROOT
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-in-a-box
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: ml-project   # ⚠️ IMPORTANTISSIMO
  source:
    repoURL: https://github.com/acicfede/mlops-demo-apex.git
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: trueapiVersion: argoproj.io/v1alpha1

