apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: monitoring-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          command: ["mlflow", "server"]
          args:
            - "--backend-store-uri=postgresql://admin:admin@postgresql.monitoring-tools.svc.cluster.local:5432/db"
            - "--default-artifact-root=s3://mlflow/"
            - "--host=0.0.0.0"
            - "--port=5000"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: monitoring-tools
spec:
  selector:
    app: mlflow
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow
  namespace: monitoring-tools
spec:
  to:
    kind: Service
    name: mlflow
  port:
    targetPort: 5000
  tls:
    termination: edge

