apiVersion: batch/v1
kind: Job
metadata:
  name: clone-pipeline-skeleton
  namespace: ml
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: clone-repo
          image: alpine/git:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Clonazione repo in directory temporanea..."
              git clone https://github.com/acicfede/pipeline-skeleton.git /tmp/repo

              echo "Pulizia contenuto PVC..."
              rm -rf /opt/app-root/src/*

              echo "Copia dei file dentro il PVC..."
              cp -R /tmp/repo/* /opt/app-root/src/

              echo "Operazione completata!"
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: data-lab-pvc

