apiVersion: batch/v1
kind: Job
metadata:
  name: clone-pipeline-skeleton
  namespace: ml
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: clone-repo
          image: alpine/git:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Pulizia directory /opt/app-root/src..."
              rm -rf /opt/app-root/src/*
              echo "✅ Clonazione repository pipeline-skeleton..."
              git clone https://github.com/acicfede/pipeline-skeleton.git /opt/app-root/src
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: data-lab-pvc
