apiVersion: batch/v1
kind: Job
metadata:
  name: clone-pipeline-skeleton-2
  namespace: ml
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc
      containers:
        - name: clone-repo
          image: alpine/git:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args: |
            set -e
            echo "Clonazione repo..."
            git clone https://github.com/acicfede/pipeline-skeleton.git /tmp/repo

            echo "Pulizia repo/ nel PVC..."
            mkdir -p /opt/app-root/src/repo
            rm -rf /opt/app-root/src/repo/*
            rm -rf /opt/app-root/src/repo/.[!.]*
            rm -rf /opt/app-root/src/repo/.??*

            echo "Rimozione pre-filled del Workbench..."
            rm -rf /opt/app-root/src/pre-filled

            echo "Copia dei file nel PVC..."
            cp -R /tmp/repo/* /opt/app-root/src/repo/

            echo "Impostazione permessi corretti..."
            # UID 1000 è l'utente del Workbench
            chown -R 1000:1000 /opt/app-root/src/repo
            chmod -R u+rwX /opt/app-root/src/repo

            echo "Operazione completata!"
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src

