apiVersion: batch/v1
kind: Job
metadata:
  name: clone-pipeline-skeleton-2
  namespace: ml
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc
      containers:
        - name: clone-repo
          image: alpine/git:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              echo "Clonazione repo in directory temporanea..."
              git clone https://github.com/acicfede/pipeline-skeleton.git /tmp/repo

              echo "Pulizia COMPLETA della sottodirectory PVC..."
              mkdir -p /opt/app-root/src/repo
              rm -rf /opt/app-root/src/repo/*
              rm -rf /opt/app-root/src/repo/.[!.]*
              rm -rf /opt/app-root/src/repo/.??*

              echo "Rimozione cartella pre-filled dal repo temporaneo..."
              rm -rf /tmp/repo/pre-filled

              echo "Copia dei file dentro la sottodirectory del PVC..."
              cp -R /tmp/repo/* /opt/app-root/src/repo/

              echo "Operazione completata!"
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src

