apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: data-lab
  namespace: ml
  labels:
    app: data-lab
spec:
  template:
    spec:
      serviceAccountName: data-lab
      initContainers:
        - name: clone-repo
          image: alpine/git:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /opt/app-root/src
              if [ ! -d ".git" ]; then
                git clone https://github.com/acicfede/pipeline-skeleton.git .
              else
                echo "Repository già presente, faccio git pull..."
                git config --global --add safe.directory /opt/app-root/src
                git pull
              fi
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
      containers:
        - name: data-lab
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.2
          env:
            - name: NOTEBOOK_ARGS
              value: |
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/ml/data-lab
                --ServerApp.quit_button=False
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
            - mountPath: /dev/shm
              name: shm
          workingDir: /opt/app-root/src
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: data-lab-pvc
        - emptyDir:
            medium: Memory
          name: shm

