apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuovo-workbench-pvc
  namespace: ml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-csi
