apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-lab-pvc
  namespace: ml
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mcp-pf-fs-storageclass
