apiVersion: batch/v1
kind: Job
metadata:
  name: untitled1-pipeline-job
  namespace: ml
spec:
  template:
    spec:
      serviceAccountName: pipeline-runner
      restartPolicy: Never
      containers:
      - name: elyra-runner
        image: quay.io/modh/runtime-images@sha256:2932e07edbcbc54e68959cc6bc5c16c6b07766453a3ac655bdc33b844108c541
        command:
          - sh
          - -c
          - |
            mkdir -p /workspace/jupyter-work-dir
            cd /workspace/jupyter-work-dir
            [[ -f bootstrapper.py ]] || curl -L https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py -o bootstrapper.py
            [[ -f requirements-elyra.txt ]] || curl -L https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt -o requirements-elyra.txt
            python3 -m pip install packaging
            python3 -m pip freeze > requirements-current.txt
            # Skip SSL verification for self-signed cert
            export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
            export PYTHONHTTPSVERIFY=0
            export REQUESTS_CA_BUNDLE=""
            export CURL_CA_BUNDLE=""
            python3 bootstrapper.py --pipeline-name "untitled1" \
              --cos-endpoint "https://minio-api-ml.apps.privateailab.acic.accenture" \
              --cos-bucket "mlpipeline-artifacts" \
              --cos-directory "untitled1-$(date +%s)" \
              --cos-dependencies-archive "Part1-Data-Cleaning.tar.gz" \
              --file "/workspace/pipelines/Part1-Data-Cleaning.ipynb"
        volumeMounts:
          - name: pipeline-files
            mountPath: /workspace/pipelines
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-secret
                key: AWS_SECRET_ACCESS_KEY
      volumes:
        - name: pipeline-files
          configMap:
            name: pipeline-files-configmap
  backoffLimit: 1
