apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: website-ingestion-pipeline
  namespace: ml
  annotations:
    argocd.argoproj.io/tracking-id: 'kfp-pipeline-composer-ai-apps:tekton.dev/Pipeline:ml/website-ingestion-pipeline'
spec:
  description: >
    Clones the repo, builds a Python image and executes a Jupyter notebook
    to launch a Kubeflow pipeline for website ingestion.
  params:
    - name: GIT_URL
      type: string
      default: "https://github.com/acicfede/mlops-demo-apex.git"
    - name: GIT_REVISION
      type: string
      default: "main"
    - name: PYTHON_IMAGE
      type: string
      default: "quay.io/openshift-python/python-311-rhel8:latest"
    - name: TARGET_IMAGE
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/ml/dspa"
    - name: NOTEBOOK_PATH
      type: string
      default: "Check_for_new_docs.ipynb"
    - name: PATH_CONTEXT
      type: string
      default: "pipelines"
    - name: WEBSITE_URL
      type: string
      default: "https://www.redhat.com/en/topics/containers/red-hat-openshift-okd"
    - name: VECTORDB_INDEX
      type: string
      default: "WebScrapedData"
    - name: KUBEFLOW_ENDPOINT
      type: string
      default: "https://ds-pipeline-dspa-ml.apps.privateailab.acic.accenture"

  workspaces:
    - name: source

  tasks:
    - name: git-clone
      taskRef:
        kind: Task
        name: git-clone
        resolver: cluster
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: source

    - name: s2i-python
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: s2i-python
        resolver: cluster
      params:
        - name: VERSION
          value: $(params.PYTHON_IMAGE)
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)  # inside the workspace
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
      workspaces:
        - name: source
          workspace: source

    - name: execute-notebook
      runAfter:
        - s2i-python
      taskRef:
        kind: Task
        name: execute-kubeflow-pipeline
      params:
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
        - name: TAG
          value: latest
        - name: NOTEBOOK_PATH
          value: $(params.PATH_CONTEXT)/$(params.NOTEBOOK_PATH)
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
        - name: WEBSITE_URL
          value: $(params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(params.VECTORDB_INDEX)
      workspaces:
        - name: source
          workspace: source

