apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: website-ingestion-pipeline
  namespace: ml
  annotations:
    argocd.argoproj.io/tracking-id: 'kfp-pipeline-composer-ai-apps:tekton.dev/Pipeline:ml/website-ingestion-pipeline'
spec:
  description: >
    Pipeline that clones a repository, builds a Python image with Buildah,
    and executes a Jupyter notebook to launch a Kubeflow pipeline.
  params:
    - name: GIT_URL
      type: string
      default: "https://github.com/acicfede/mlops-demo-apex.git"
    - name: GIT_REVISION
      type: string
      default: "main"
    - name: WEBSITE_URL
      type: string
      default: "https://www.redhat.com/en/topics/containers/red-hat-openshift-okd"
    - name: VECTORDB_INDEX
      type: string
      default: "WebScrapedData"
    - name: NOTEBOOK_PATH
      type: string
      default: "Check_for_new_docs.ipynb"
    - name: PATH_CONTEXT
      type: string
      default: "pipelines"
    - name: BASE_IMAGE
      type: string
      default: "quay.io/openshift/python-311-rhel8:latest"
    - name: TARGET_IMAGE
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/ml/dspa"
    - name: KUBEFLOW_ENDPOINT
      type: string
      default: "https://ds-pipeline-dspa-ml.apps.privateailab.acic.accenture"

  workspaces:
    - name: source

  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: source

    - name: build-python-image
      runAfter:
        - git-clone
      taskSpec:
        params:
          - name: BASE_IMAGE
          - name: TARGET_IMAGE
          - name: PATH_CONTEXT
        workspaces:
          - name: source
        steps:
          - name: build
            image: quay.io/buildah/stable:latest
            workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
            command:
              - buildah
            args:
              - bud
              - -t
              - $(params.TARGET_IMAGE)
              - --build-arg
              - BASE_IMAGE=$(params.BASE_IMAGE)
              - .
      params:
        - name: BASE_IMAGE
          value: $(params.BASE_IMAGE)
        - name: TARGET_IMAGE
          value: $(params.TARGET_IMAGE)
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
      workspaces:
        - name: source
          workspace: source

    - name: execute-kubeflow-pipeline
      runAfter:
        - build-python-image
      taskRef:
        kind: Task
        name: execute-kubeflow-pipeline
      params:
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
        - name: TAG
          value: latest
        - name: NOTEBOOK_PATH
          value: $(params.NOTEBOOK_PATH)
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
        - name: WEBSITE_URL
          value: $(params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(params.VECTORDB_INDEX)

