apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: website-ingestion-pipeline
  namespace: ml
spec:
  params:
    - name: GIT_URL
      type: string
      description: Repository URL
      default: "https://github.com/redhat-composer-ai/data-ingestion"

    - name: GIT_REVISION
      type: string
      default: "main"

    - name: WEBSITE_URL
      type: string
      description: The website URL to be ingested
      default: "https://www.redhat.com/en/topics/containers/red-hat-openshift-okd"

    - name: VECTORDB_INDEX
      type: string
      description: The vector DB index where the website scrape will be ingested
      default: "WebScrapedData"

    - name: KFP_SCRIPT
      type: string
      description: Path to the Python script or notebook for Kubeflow pipeline
      default: "website-ingestion-pipeline.py"

    - name: PATH_CONTEXT
      type: string
      description: Directory of the pipeline script
      default: "kfp/website-ingestor"

    - name: PYTHON_IMAGE
      type: string
      default: "3.11-ubi9"

    - name: TARGET_IMAGE
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/ml/dspa"

    - name: KUBEFLOW_ENDPOINT
      type: string
      default: "https://ds-pipeline-dspa-ml.apps.privateailab.acic.accenture"

  workspaces:
    - name: source

  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: source

    - name: s2i-python
      runAfter:
        - git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: s2i-python
          - name: namespace
            value: openshift-pipelines
      params:
        - name: VERSION
          value: $(params.PYTHON_IMAGE)
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
      workspaces:
        - name: source
          workspace: source

    - name: execute-website-ingestion-kubeflow-pipeline
      runAfter:
        - s2i-python
      taskRef:
        kind: Task
        name: execute-website-ingestion-kubeflow-pipeline
      params:
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
        - name: TAG
          value: latest
        - name: SCRIPT
          value: $(params.KFP_SCRIPT)
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
        - name: WEBSITE_URL
          value: $(params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(params.VECTORDB_INDEX)


