apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: website-ingestion-pipeline
  namespace: ml
  annotations:
    argocd.argoproj.io/tracking-id: 'kfp-pipeline-composer-ai-apps:tekton.dev/Pipeline:ml/website-ingestion-pipeline'
spec:
  description: >
    Pipeline that clones a repository and executes
    a Jupyter notebook to launch a Kubeflow pipeline for website ingestion.
  params:
    - name: GIT_URL
      type: string
      default: "https://github.com/acicfede/mlops-demo-apex.git"
      description: Repository URL
    - name: GIT_REVISION
      type: string
      default: "main"
    - name: WEBSITE_URL
      type: string
      default: "https://www.redhat.com/en/topics/containers/red-hat-openshift-okd"
      description: Website to ingest
    - name: VECTORDB_INDEX
      type: string
      default: "WebScrapedData"
      description: Target vector DB index
    - name: NOTEBOOK_PATH
      type: string
      default: "Check_for_new_docs.ipynb"
      description: Path of the notebook to execute
    - name: PATH_CONTEXT
      type: string
      default: "pipelines"
      description: Directory of the notebook
    - name: PYTHON_IMAGE
      type: string
      default: "quay.io/openshift/python-311-rhel8:latest"

  workspaces:
    - name: source

  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: source

    - name: execute-notebook
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: execute-kubeflow-pipeline
      params:
        - name: IMAGE
          value: $(params.PYTHON_IMAGE)
        - name: TAG
          value: latest
        - name: NOTEBOOK_PATH
          value: $(params.NOTEBOOK_PATH)
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
        - name: WEBSITE_URL
          value: $(params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(params.VECTORDB_INDEX)
