apiVersion: kubeflow.org/v1beta1
kind: Pipeline
metadata:
  name: untitled1
  namespace: ml
spec:
  pipelineSpec:
    components:
      comp-run-a-file:
        executorLabel: exec-run-a-file
      comp-run-a-file-2:
        executorLabel: exec-run-a-file-2
      comp-run-a-file-3:
        executorLabel: exec-run-a-file-3
    deploymentSpec:
      executors:
        exec-run-a-file:
          container:
            image: quay.io/modh/runtime-images@sha256:2932e07edbcbc54e68959cc6bc5c16c6b07766453a3ac655bdc33b844108c541
            command: ["sh","-c"]
            args:
            - 'mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir
              && [[ -e /opt/app-root/bin/utils/bootstrapper.py ]] && cp /opt/app-root/bin/utils/bootstrapper.py . || curl -fsSL https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py -o bootstrapper.py
              && [[ -e /opt/app-root/bin/utils/requirements-elyra.txt ]] && cp /opt/app-root/bin/utils/requirements-elyra.txt . || curl -fsSL https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt -o requirements-elyra.txt
              && python3 -m pip install packaging
              && python3 -m pip freeze > requirements-current.txt
              && python3 bootstrapper.py --pipeline-name "untitled1" --cos-endpoint "https://minio-api-ml.apps.privateailab.acic.accenture" --cos-bucket "mlpipeline-artifacts" --cos-directory "untitled1-1024150021" --cos-dependencies-archive "Part 1 - Data Cleaning-ef9b9501-27a3-4700-a2bf-39909d67c0be.tar.gz" --file "examples/pipelines/run-generic-pipelines-on-kubeflow-pipelines/Part 1 - Data Cleaning.ipynb"'
            env:
              - name: ELYRA_RUNTIME_ENV
                value: kfp
              - name: ELYRA_ENABLE_PIPELINE_INFO
                value: "True"
              - name: ELYRA_WRITABLE_CONTAINER_DIR
                value: /tmp
              - name: ELYRA_RUN_NAME
                value: "{{workflow.uid}}"
          secretAsEnv:
            - keyToEnv:
                - envVar: AWS_ACCESS_KEY_ID
                  secretKey: AWS_ACCESS_KEY_ID
                - envVar: AWS_SECRET_ACCESS_KEY
                  secretKey: AWS_SECRET_ACCESS_KEY
              secretName: minio-secret

        exec-run-a-file-2:
          container:
            image: quay.io/modh/runtime-images@sha256:2932e07edbcbc54e68959cc6bc5c16c6b07766453a3ac655bdc33b844108c541
            command: ["sh","-c"]
            args:
            - 'mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir
              && [[ -e /opt/app-root/bin/utils/bootstrapper.py ]] && cp /opt/app-root/bin/utils/bootstrapper.py . || curl -fsSL https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py -o bootstrapper.py
              && [[ -e /opt/app-root/bin/utils/requirements-elyra.txt ]] && cp /opt/app-root/bin/utils/requirements-elyra.txt . || curl -fsSL https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt -o requirements-elyra.txt
              && python3 -m pip install packaging
              && python3 -m pip freeze > requirements-current.txt
              && python3 bootstrapper.py --pipeline-name "untitled1" --cos-endpoint "https://minio-api-ml.apps.privateailab.acic.accenture" --cos-bucket "mlpipeline-artifacts" --cos-directory "untitled1-1024150021" --cos-dependencies-archive "Part 2 - Data Analysis-a54a8b17-8b07-4309-83ff-5aab4b62b6ad.tar.gz" --file "examples/pipelines/run-generic-pipelines-on-kubeflow-pipelines/Part 2 - Data Analysis.ipynb"'
            env:
              - name: ELYRA_RUNTIME_ENV
                value: kfp
              - name: ELYRA_ENABLE_PIPELINE_INFO
                value: "True"
              - name: ELYRA_WRITABLE_CONTAINER_DIR
                value: /tmp
              - name: ELYRA_RUN_NAME
                value: "{{workflow.uid}}"
          secretAsEnv:
            - keyToEnv:
                - envVar: AWS_ACCESS_KEY_ID
                  secretKey: AWS_ACCESS_KEY_ID
                - envVar: AWS_SECRET_ACCESS_KEY
                  secretKey: AWS_SECRET_ACCESS_KEY
              secretName: minio-secret

        exec-run-a-file-3:
          container:
            image: quay.io/modh/runtime-images@sha256:2932e07edbcbc54e68959cc6bc5c16c6b07766453a3ac655bdc33b844108c541
            command: ["sh","-c"]
            args:
            - 'mkdir -p ./jupyter-work-dir && cd ./jupyter-work-dir
              && [[ -e /opt/app-root/bin/utils/bootstrapper.py ]] && cp /opt/app-root/bin/utils/bootstrapper.py . || curl -fsSL https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/elyra/kfp/bootstrapper.py -o bootstrapper.py
              && [[ -e /opt/app-root/bin/utils/requirements-elyra.txt ]] && cp /opt/app-root/bin/utils/requirements-elyra.txt . || curl -fsSL https://raw.githubusercontent.com/opendatahub-io/elyra/v4.2.0/etc/generic/requirements-elyra.txt -o requirements-elyra.txt
              && python3 -m pip install packaging
              && python3 -m pip freeze > requirements-current.txt
              && python3 bootstrapper.py --pipeline-name "untitled1" --cos-endpoint "https://minio-api-ml.apps.privateailab.acic.accenture" --cos-bucket "mlpipeline-artifacts" --cos-directory "untitled1-1024150021" --cos-dependencies-archive "Part 3 - Time Series Forecasting-3009c883-57ce-477d-9fc5-ce1a6f0a113b.tar.gz" --file "examples/pipelines/run-generic-pipelines-on-kubeflow-pipelines/Part 3 - Time Series Forecasting.ipynb"'
            env:
              - name: ELYRA_RUNTIME_ENV
                value: kfp
              - name: ELYRA_ENABLE_PIPELINE_INFO
                value: "True"
              - name: ELYRA_WRITABLE_CONTAINER_DIR
                value: /tmp
              - name: ELYRA_RUN_NAME
                value: "{{workflow.uid}}"
          secretAsEnv:
            - keyToEnv:
                - envVar: AWS_ACCESS_KEY_ID
                  secretKey: AWS_ACCESS_KEY_ID
                - envVar: AWS_SECRET_ACCESS_KEY
                  secretKey: AWS_SECRET_ACCESS_KEY
              secretName: minio-secret
