apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: website-ingestion-pipeline
  namespace: ml
spec:
  params:
    - name: GIT_URL
      type: string
      default: "https://github.com/acicfede/mlops-demo-apex.git"
    - name: GIT_REVISION
      type: string
      default: "main"
    - name: WEBSITE_URL
      type: string
      default: "https://www.redhat.com/en/topics/containers/red-hat-openshift-okd"
    - name: VECTORDB_INDEX
      type: string
      default: "WebScrapedData"
    - name: NOTEBOOK_PATH
      type: string
      default: "Check_for_new_docs.ipynb"
    - name: PATH_CONTEXT
      type: string
      default: "pipelines"
    - name: BASE_IMAGE
      type: string
      default: "quay.io/openshift/python-311-rhel8:latest"
    - name: TARGET_IMAGE
      type: string
      default: "image-registry.openshift-image-registry.svc:5000/ml/dspa"
    - name: KUBEFLOW_ENDPOINT
      type: string
      default: "https://ds-pipeline-dspa-ml.apps.privateailab.acic.accenture"
  workspaces:
    - name: source
  tasks:
    - name: clone
      taskRef:
        name: git-clone-task
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: source

    - name: build-image
      runAfter:
        - clone
      taskRef:
        name: build-python-image
      params:
        - name: BASE_IMAGE
          value: $(params.BASE_IMAGE)
        - name: TARGET_IMAGE
          value: $(params.TARGET_IMAGE)
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
      workspaces:
        - name: source
          workspace: source

    - name: execute-notebook
      runAfter:
        - build-image
      taskRef:
        name: execute-notebook
      params:
        - name: IMAGE
          value: $(params.TARGET_IMAGE)
        - name: NOTEBOOK_PATH
          value: $(params.NOTEBOOK_PATH)
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
        - name: WEBSITE_URL
          value: $(params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(params.VECTORDB_INDEX)
      workspaces:
        - name: source
          workspace: source
