apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: website-ingestion-pipeline
  namespace: ml
spec:
  params:
    - name: GIT_URL
      type: string
      default: "https://github.com/acicfede/mlops-demo-apex.git"
    - name: GIT_REVISION
      type: string
      default: "main"
    - name: PATH_CONTEXT
      type: string
      default: "pipelines"
    - name: NOTEBOOK_PATH
      type: string
      default: "Check_for_new_docs.ipynb"
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: URL
          value: $(params.GIT_URL)
        - name: REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: output
          workspace: source

    - name: execute-notebook
      runAfter:
        - git-clone
      taskRef:
        name: execute-kubeflow-pipeline
        kind: Task
      params:
        - name: NOTEBOOK_PATH
          value: $(params.NOTEBOOK_PATH)
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
      workspaces:
        - name: source
          workspace: source

