apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: execute-kubeflow-pipeline
  namespace: ml
spec:
  params:
    - name: IMAGE
      type: string
    - name: TAG
      type: string
      default: latest
    - name: NOTEBOOK_PATH
      type: string
    - name: KUBEFLOW_ENDPOINT
      type: string
    - name: WEBSITE_URL
      type: string
    - name: VECTORDB_INDEX
      type: string
  workspaces:
    - name: source
  steps:
    - name: execute-notebook
      image: $(params.IMAGE):$(params.TAG)
      script: |
        #!/bin/sh
        cd $(workspaces.source.path)
        jupyter nbconvert --to notebook --execute $(params.NOTEBOOK_PATH)
        # Qui puoi aggiungere il comando Python per invocare Kubeflow
        # es: python run_pipeline.py --endpoint $(params.KUBEFLOW_ENDPOINT) --url $(params.WEBSITE_URL)


