apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: s2i-python
  namespace: ml
spec:
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
    - name: VERSION
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/openshift/origin-s2i-python:3.11
      script: |
        #!/bin/sh
        cd $(workspaces.source.path)/$(params.CONTEXT)
        s2i build . $(params.IMAGE):$(params.VERSION)


