apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: execute-notebook
spec:
  params:
    - name: IMAGE
      description: Container image with Python + Jupyter installed
    - name: TAG
      description: Image tag
      default: "latest"
    - name: NOTEBOOK_PATH
      description: Path to the notebook to execute, relative to workspace
      default: "Untitled-Copy2.ipynb"   # Aggiorna con un notebook esistente nella repo
  workspaces:
    - name: source
      description: Workspace containing the repo
  steps:
    - name: execute-notebook
      image: "$(params.IMAGE):$(params.TAG)"
      workingDir: "$(workspaces.source.path)"
      script: |
        #!/usr/bin/env sh
        set -e

        echo "Eseguendo notebook: $(params.NOTEBOOK_PATH)"
        # Aggiorna pip e installa i pacchetti necessari
        pip install --upgrade pip jupyter nbconvert ipykernel

        # Esegui il notebook in-place
        jupyter nbconvert --execute $(params.NOTEBOOK_PATH) --to notebook --inplace



