apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: execute-kubeflow-pipeline
  namespace: ml
spec:
  params:
    - name: NOTEBOOK_PATH
      type: string
    - name: PATH_CONTEXT
      type: string
  workspaces:
    - name: source
  steps:
    - name: run-notebook
      image: python:3.11-slim
      script: |
        #!/bin/sh
        cd $(workspaces.source.path)/$(params.PATH_CONTEXT)
        jupyter nbconvert --to notebook --execute $(params.NOTEBOOK_PATH)


