apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: execute-website-ingestion-kubeflow-pipeline
  namespace: ml
spec:
  description: "Esegue il notebook e avvia la pipeline Kubeflow"
  params:
    - name: IMAGE
      type: string
    - name: TAG
      type: string
      default: "latest"
    - name: SCRIPT
      type: string
    - name: KUBEFLOW_ENDPOINT
      type: string
    - name: WEBSITE_URL
      type: string
    - name: VECTORDB_INDEX
      type: string
  steps:
    - name: execute-python
      image: $(params.IMAGE):$(params.TAG)
      script: |
        python $(params.SCRIPT)

