apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: ml
spec:
  params:
    - name: URL
      type: string
    - name: REVISION
      type: string
      default: main
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone -b $(params.REVISION) $(params.URL) $(workspaces.output.path)



