apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: execute-website-ingestion-kubeflow-pipeline
  namespace: ml
spec:
  description: This task will execute a Python script, triggering a Kubeflow pipeline
  params:
    - name: IMAGE
      description: The image used to execute the script
      type: string
    - name: TAG
      description: The tag for the image
      type: string
      default: latest
    - name: SCRIPT
      description: The location of the script to be executed
      type: string
    - name: KUBEFLOW_ENDPOINT
      description: The endpoint URL for Kubeflow
      type: string
      default: 'https://ds-pipeline-dspa-ml.apps.privateailab.acic.accenture'
    - name: WEBSITE_URL
      description: The website url to be ingested
      type: string
      default: 'https://www.redhat.com/en/topics/containers/red-hat-openshift-okd'
    - name: VECTORDB_INDEX
      description: The vector db index where the website scrape will be ingested
      type: string
      default: WebScrapedData
  steps:
    - name: execute-python
      image: '$(inputs.params.IMAGE):$(inputs.params.TAG)'
      env:
        - name: WEBSITE_URL
          value: $(inputs.params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(inputs.params.VECTORDB_INDEX)
        - name: KUBEFLOW_ENDPOINT
          value: $(inputs.params.KUBEFLOW_ENDPOINT)
        - name: BASE_IMAGE
          value: '$(inputs.params.IMAGE):$(inputs.params.TAG)'
        - name: CLUSTER_DOMAIN
          value: apps.cluster-84nkq.84nkq.sandbox118.opentlc.com
      script: |
        python $(inputs.params.SCRIPT)
