apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: execute-notebook
  namespace: ml
spec:
  params:
    - name: PATH_CONTEXT
      type: string
      default: "pipelines"
    - name: NOTEBOOK_PATH
      type: string
      default: "Check_for_new_docs.ipynb"
  workspaces:
    - name: source
  steps:
    - name: run-notebook
      image: python:3.11-slim
      script: |
        #!/bin/sh
        cd $(workspaces.source.path)/$(params.PATH_CONTEXT)
        pip install jupyter nbconvert
        jupyter nbconvert --to notebook --execute $(params.NOTEBOOK_PATH)


