apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: execute-notebook-kubeflow
  namespace: composer-ai-apps
spec:
  description: Execute a Jupyter notebook triggering a Kubeflow pipeline
  params:
    - name: IMAGE
      description: The image used to execute the notebook
      type: string
    - name: TAG
      description: The tag for the image
      type: string
      default: "latest"
    - name: NOTEBOOK
      description: The notebook to be executed
    - name: KUBEFLOW_ENDPOINT
      description: The endpoint URL for Kubeflow
      default: "https://ds-pipeline-dspa-ml.apps.privateailab.acic.accenture"
    - name: WEBSITE_URL
      description: The website url to be ingested
      default: "https://www.redhat.com/en/topics/containers/red-hat-openshift-okd"
    - name: VECTORDB_INDEX
      description: The vector db index where the website scrape will be ingested
      default: "WebScrapedData"
  steps:
    - name: execute-notebook
      image: $(inputs.params.IMAGE):$(inputs.params.TAG)
      env:
        - name: WEBSITE_URL
          value: $(inputs.params.WEBSITE_URL)
        - name: VECTORDB_INDEX
          value: $(inputs.params.VECTORDB_INDEX)
        - name: KUBEFLOW_ENDPOINT
          value: $(inputs.params.KUBEFLOW_ENDPOINT)
      script: |
        # Install papermill if not already present
        pip install --no-cache-dir papermill
        # Execute the notebook with parameters
        papermill $(inputs.params.NOTEBOOK) output.ipynb \
          -p WEBSITE_URL $(WEBSITE_URL) \
          -p VECTORDB_INDEX $(VECTORDB_INDEX)




