apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-python-image
  namespace: ml
spec:
  params:
    - name: BASE_IMAGE
      type: string
    - name: TARGET_IMAGE
      type: string
    - name: CONTEXT
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.40.0
      script: |
        #!/bin/sh
        set -e
        echo "Building Python image..."
        cd $(workspaces.source.path)/$(params.CONTEXT)
        ls -l
        buildah bud -t $(params.TARGET_IMAGE) --build-arg BASE_IMAGE=$(params.BASE_IMAGE) .

