apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: execute-kubeflow-pipeline
  namespace: ml
  labels:
    app.kubernetes.io/instance: elyra-pipeline
spec:
  description: Execute a Jupyter notebook to launch a Kubeflow pipeline
  params:
    - name: IMAGE
      type: string
    - name: TAG
      type: string
      default: latest
    - name: NOTEBOOK_PATH
      type: string
    - name: KUBEFLOW_ENDPOINT
      type: string
    - name: WEBSITE_URL
      type: string
    - name: VECTORDB_INDEX
      type: string
    - name: PATH_CONTEXT
      type: string
  workspaces:
    - name: source
  steps:
    - name: run-notebook
      image: "$(inputs.params.IMAGE):$(inputs.params.TAG)"
      script: |
        #!/bin/sh
        set -e

        echo "Using Kubeflow endpoint: $(inputs.params.KUBEFLOW_ENDPOINT)"
        echo "Vector DB Index: $(inputs.params.VECTORDB_INDEX)"
        echo "Website URL: $(inputs.params.WEBSITE_URL)"

        # spostarsi nella directory corretta
        cd $(workspaces.source.path)/$(inputs.params.PATH_CONTEXT)

        # installare dipendenze se servono
        pip install --no-cache-dir jupyter pandas numpy

        # eseguire il notebook
        jupyter nbconvert --to notebook --execute $(inputs.params.NOTEBOOK_PATH)

