---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: mlflow
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'mlflow'
        orgId: 1
        folder: 'MLflow'
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /etc/grafana/provisioning/dashboards/mlflow

# --------------------------------------
# PVC for Grafana
# --------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mcp-pf-fs-storageclass
---
# --------------------------------------
# ConfigMap: MLflow PostgreSQL datasource
# --------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-mlflow
  namespace: mlflow
data:
  mlflow.yaml: |
    apiVersion: 1
    datasources:
      - name: MLflow-PostgreSQL
        type: postgres
        access: proxy
        url: postgresql.mlflow.svc.cluster.local:5432
        user: admin
        secureJsonData:
          password: admin
        jsonData:
          sslmode: disable
        database: db
        isDefault: false
---
# --------------------------------------
# ConfigMap: Prometheus datasource
# --------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-prometheus
  namespace: mlflow
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated:9090
        isDefault: true
---
# --------------------------------------
# ConfigMap: Loki datasource
# --------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ds-loki
  namespace: mlflow
data:
  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
---
# --------------------------------------
# Deployment Grafana
# --------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mlflow
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:9.5.2
          imagePullPolicy: IfNotPresent

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin

          ports:
            - containerPort: 3000
              protocol: TCP

          volumeMounts:
            # ------------------------------
            # Persistent storage
            # ------------------------------
            - name: grafana-storage
              mountPath: /var/lib/grafana

            # ------------------------------
            # Datasource provisioning
            # ------------------------------
            - name: grafana-ds-mlflow
              mountPath: /etc/grafana/provisioning/datasources/mlflow.yaml
              subPath: mlflow.yaml

            - name: grafana-ds-prometheus
              mountPath: /etc/grafana/provisioning/datasources/prometheus.yaml
              subPath: prometheus.yaml

            - name: grafana-ds-loki
              mountPath: /etc/grafana/provisioning/datasources/loki.yaml
              subPath: loki.yaml

            # ------------------------------
            # Dashboard provider
            # ------------------------------
            - name: grafana-dashboard-providers
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml

            # ------------------------------
            # MLflow dashboard (JSON)
            # ConfigMap created automatically by Kustomize
            # ------------------------------
            - name: grafana-dashboard-mlflow
              mountPath: /etc/grafana/provisioning/dashboards/mlflow/mlflow-training-dashboard.json
              subPath: mlflow-training-dashboard.json

      volumes:
        # PVC storage for Grafana data
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-data

        # Datasource files provisioned from ConfigMaps
        - name: grafana-ds-mlflow
          configMap:
            name: grafana-ds-mlflow

        - name: grafana-ds-prometheus
          configMap:
            name: grafana-ds-prometheus

        - name: grafana-ds-loki
          configMap:
            name: grafana-ds-loki

        # Dashboard provider
        - name: grafana-dashboard-providers
          configMap:
            name: grafana-dashboard-providers

        # Dashboard JSON created by configMapGenerator
        - name: grafana-dashboard-mlflow
          configMap:
            name: grafana-dashboard-mlflow

      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
---
# --------------------------------------
# Service Grafana
# --------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: mlflow
spec:
  selector:
    app: grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---
# --------------------------------------
# Route Grafana (OpenShift)
# --------------------------------------
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: mlflow
spec:
  to:
    kind: Service
    name: grafana
  port:
    targetPort: http
  tls:
    termination: edge
