---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
  namespace: mlflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mlflow-server
  template:
    metadata:
      labels:
        name: mlflow-server
    spec:
      serviceAccountName: mlflow
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: mlflow
          image: docker.io/hemaveeradhi/mlflow:amd64
          imagePullPolicy: IfNotPresent
          command: ["mlflow"]
          args:
            - server
            - --host
            - 0.0.0.0
            - --backend-store-uri
            - postgresql://admin:admin@postgresql.mlflow.svc.cluster.local:5432/db?sslmode=disable
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi

      volumes:
        - name: proxy-tls
          secret:
            secretName: proxy-tls

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
  namespace: mlflow
spec:
  type: ClusterIP
  selector:
    name: mlflow-server
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow
  namespace: mlflow
spec:
  to:
    kind: Service
    name: mlflow-server
  port:
    targetPort: http
  tls:
    termination: edge 

