apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: pipelines-definition
  namespace: ml
spec:
  dspVersion: v2
  apiServer:
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
  database:
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  objectStorage:
    externalStorage:
      bucket: mlpipeline-artifacts
      host: minio-service.ml.svc
      scheme: http
      s3CredentialsSecret:
        secretName: minio-secret
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
  persistenceAgent:
    deploy: true
    numWorkers: 2
  scheduledWorkflow:
    deploy: true
    cronScheduleTimezone: UTC
