apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: granite-3.1-2b-instruct
  namespace: ml
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/accelerator-name: ""
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/runtime-version: v0.10.1.1
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime
    openshift.io/display-name: granite-3.1-2b-instruct
  labels:
    opendatahub.io/dashboard: "true"

spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"

  containers:
    - name: kserve-container
      image: registry.redhat.io/rhoai/odh-vllm-cuda-rhel9@sha256:fb84fbf103bf450ef5b060fc5f21a9cf16b166dba207a3c50aa91bccd919d604
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name=granite-3.1-2b-instruct
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: shm
          mountPath: /dev/shm

  multiModel: false

  supportedModelFormats:
    - name: vLLM
      autoSelect: true

  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi

---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-3.1-2b-instruct
  namespace: ml
  annotations:
    opendatahub.io/hardware-profile-namespace: redhat-ods-applications
    opendatahub.io/legacy-hardware-profile-name: migrated-gpu-mglzi-serving
    openshift.io/display-name: granite-3.1-2b-instruct
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
  finalizers:
    - odh.inferenceservice.finalizers
    - inferenceservice.finalizers

spec:
  predictor:
    automountServiceAccountToken: false
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: granite-3.1-2b-instruct
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.1-2b-instruct
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"

