apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: llama-32-3b-instruct
  namespace: ml
  annotations:
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: vLLM ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: "true"

spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"

  containers:
    - name: kserve-container
      image: quay.io/modh/vllm@sha256:0d55419f3d168fd80868a36ac89815dded9e063937a8409b7edf3529771383f3
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
        - --dtype=half
        - --max_model_len=8192
        - --gpu_memory_utilization=.95
        - --enable-auto-tool-choice
        - --tool_call_parser=llama3_json
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      ports:
        - containerPort: 8080
          protocol: TCP

  multiModel: false

  supportedModelFormats:
    - name: vLLM
      autoSelect: true
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama-32-3b-instruct
  namespace: ml
  annotations:
    openshift.io/display-name: llama-32-3b-instruct
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"

spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      name: ""
      runtime: llama-32-3b-instruct
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct
      modelFormat:
        name: vLLM
      args:
        - --dtype=half
        - --max_model_len=8192
        - --gpu_memory_utilization=.95
        - --enable-auto-tool-choice
        - --tool_call_parser=llama3_json
      resources:
        requests:
          cpu: "4"
          memory: 8Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "8"
          memory: 10Gi
          nvidia.com/gpu: "1"
