apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: vLLM NVIDIA GPU ServingRuntime for KServe
    opendatahub.io/template-name: vllm-cuda-runtime
    openshift.io/display-name: llama32-1b
  name: llama32-1b
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - '--port=8080'
        - '--model=/mnt/models'
        - '--served-model-name={{.Name}}'
        - '--enable-auto-tool-choice'
        - '--tool-call-parser'
        - llama3_json
        - '--chat-template'
        - /app/data/template/tool_chat_template_llama3.2_json.jinja
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: registry.redhat.io/rhoai/odh-vllm-cuda-rhel9@sha256:fb84fbf103bf450ef5b060fc5f21a9cf16b166dba207a3c50aa91bccd919d604
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama-32-3b-instruct
  namespace: ml
  annotations:
    openshift.io/display-name: llama-32-3b-instruct
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: 'true'

spec:
  predictor:
    automountServiceAccountToken: false
    minReplicas: 1
    maxReplicas: 1
    model:
      name: ''
      runtime: llama32-1b
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct
      modelFormat:
        name: vLLM
      args:
        - --dtype=half
        - --max_model_len=8192
        - --gpu_memory_utilization=.95
        - --enable-auto-tool-choice
        - --tool_call_parser=llama3_json
      resources:
        requests:
          cpu: '4'
          memory: 8Gi
          nvidia.com/gpu: '1'
        limits:
          cpu: '8'
          memory: 10Gi
          nvidia.com/gpu: '1'
      container:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
