apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama-32-3b-instruct
  annotations:
    openshift.io/display-name: llama-32-3b-instruct
    serving.knative.openshift.io/enablePassthrough: 'true'
    serving.kserve.io/deploymentMode: Serverless
    sidecar.istio.io/inject: 'true'
    sidecar.istio.io/rewriteAppHTTPProbers: 'true'
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      name: ''
      runtime: llama-32-3b-instruct
      storageUri: 'oci://quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct'
      modelFormat:
        name: vLLM
      args:
        - '--dtype=half'
        - '--max_model_len=8192'
        - '--gpu_memory_utilization=.95'
        - '--enable-auto-tool-choice'
        - '--tool_call_parser=llama3_json'
      resources:
        requests:
          cpu: '4'
          memory: 8Gi
          nvidia.com/gpu: '1'
        limits:
          cpu: '8'
          memory: 10Gi
          nvidia.com/gpu: '1'
      container:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu

