---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-workbench
  namespace: ml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuovo-workbench-pvc
  namespace: ml
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-csi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: clone-pipeline-skeleton
  namespace: ml
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: ml-workbench
      containers:
        - name: clone-repo
          image: docker.io/alpine/git:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              TARGET_DIR="/opt/app-root/src/repo"

              if [ -d "$TARGET_DIR/.git" ]; then
                echo "Repository già presente, skip clone"
                exit 0
              fi

              echo "Clonazione repository pipeline-skeleton..."
              git clone https://github.com/acicfede/pipeline-skeleton.git "$TARGET_DIR"

              echo "BOOTSTRAP COMPLETATO"
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: nuovo-workbench
  namespace: ml
  labels:
    app: nuovo-workbench
  annotations:
    opendatahub.io/legacy-hardware-profile-name: migrated-gpu-mglzi-notebooks
    opendatahub.io/hardware-profile-namespace: ''
    opendatahub.io/image-display-name: "Jupyter | PyTorch LLM Compressor | CUDA | Python 3.12"
    notebooks.opendatahub.io/oauth-logout-url: "https://rhods-dashboard-redhat-ods-applications.apps.privateailab.acic.accenture/projects/ml?notebookLogout=nuovo-workbench"
    openshift.io/display-name: nuovo-workbench

spec:
  template:
    spec:
      serviceAccountName: ml-workbench
      enableServiceLinks: false

      containers:
        # =========================
        # Notebook container
        # =========================
        - name: nuovo-workbench
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-pytorch-llmcompressor:2025.2
          imagePullPolicy: Always
          workingDir: /opt/app-root/src

          ports:
            - name: notebook-port
              containerPort: 8888
              protocol: TCP

          env:
            - name: NOTEBOOK_ARGS
              value: |
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/ml/nuovo-workbench
                --ServerApp.quit_button=False

          resources:
            requests:
              cpu: "1"
              memory: 16Gi
            limits:
              cpu: "2"
              memory: 24Gi

          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
            - name: shm
              mountPath: /dev/shm

        # =========================
        # OAuth proxy (manuale)
        # =========================
        - name: oauth-proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy-rhel9
          imagePullPolicy: Always

          ports:
            - name: oauth-proxy
              containerPort: 8443
              protocol: TCP

          args:
            - --provider=openshift
            - --https-address=:8443
            - --http-address=
            - --upstream=http://localhost:8888
            - --email-domain=*
            - --skip-provider-button
            - --cookie-expire=24h0m0s
            - --cookie-secret-file=/etc/oauth/config/cookie_secret
            - --client-id=nuovo-workbench-ml-oauth-client
            - --client-secret-file=/etc/oauth/client/secret
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --logout-url=https://rhods-dashboard-redhat-ods-applications.apps.privateailab.acic.accenture/projects/ml?notebookLogout=nuovo-workbench
            - >
              --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"nuovo-workbench","namespace":"ml"}

          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

          volumeMounts:
            - name: oauth-client
              mountPath: /etc/oauth/client
            - name: oauth-config
              mountPath: /etc/oauth/config
            - name: tls-certificates
              mountPath: /etc/tls/private

      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc

        - name: shm
          emptyDir:
            medium: Memory

        - name: oauth-config
          secret:
            secretName: nuovo-workbench-oauth-config

        - name: oauth-client
          secret:
            secretName: nuovo-workbench-oauth-client

        - name: tls-certificates
          secret:
            secretName: nuovo-workbench-tls


