---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-workbench
  namespace: ml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuovo-workbench-pvc
  namespace: ml
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-csi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: clone-pipeline-skeleton-2
  namespace: ml
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: ml-workbench
      containers:
        - name: clone-repo
          image: docker.io/alpine/git:latest
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e

              echo "Installazione git..."
              dnf install -y git

              echo "Clonazione repository..."
              git clone https://github.com/acicfede/pipeline-skeleton.git /tmp/repo

              echo "Rimozione directory pre-filled di sistema..."
              rm -rf /opt/app-root/src/pre-filled || true

              echo "Pulizia directory repo nel PVC..."
              mkdir -p /opt/app-root/src/repo
              rm -rf /opt/app-root/src/repo/*

              echo "Copia repository..."
              cp -R /tmp/repo/* /opt/app-root/src/repo/

              echo "Correzione permessi (UID Workbench = 1001750000)..."
              chown -R 1001750000:1001750000 /opt/app-root/src/repo
              chmod -R u+rwX /opt/app-root/src/repo

              echo "FINITO con successo!"
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: nuovo-workbench
  namespace: ml
  labels:
    app: nuovo-workbench
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/image-display-name: "Jupyter | PyTorch LLM Compressor | CUDA | Python 3.12"
    notebooks.opendatahub.io/oauth-logout-url: "https://rhods-dashboard-redhat-ods-applications.apps.privateailab.acic.accenture/projects/ml?notebookLogout=nuovo-workbench"
    notebooks.opendatahub.io/last-image-selection: "jupyter-pytorch-llmcompressor:2025.2"
    opendatahub.io/hardware-profile-namespace: ml
    opendatahub.io/username: admin
    openshift.io/display-name: nuovo-workbench
spec:
  template:
    spec:
      serviceAccountName: ml-workbench
      enableServiceLinks: false
      containers:
        - name: nuovo-workbench
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-pytorch-llmcompressor:2025.2
          imagePullPolicy: Always
          workingDir: /opt/app-root/src
          env:
            - name: NOTEBOOK_ARGS
              value: |
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/ml/nuovo-workbench
                --ServerApp.quit_button=False
          ports:
            - containerPort: 8888
              name: notebook-port
          resources:
            requests:
              cpu: "1"
              memory: 8Gi
            limits:
              cpu: "2"
              memory: 8Gi
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: workbench-storage
            - mountPath: /dev/shm
              name: shm
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc
        - name: shm
          emptyDir:
            medium: Memory


