---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-workbench
  namespace: ml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nuovo-workbench-pvc
  namespace: ml
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-csi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: clone-pipeline-skeleton
  namespace: ml
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: ml-workbench
      containers:
        - name: clone-repo
          image: registry.access.redhat.com/ubi9/git:9.3
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail

              TARGET_DIR="/opt/app-root/src/repo"

              if [ ! -d "$TARGET_DIR/.git" ]; then
                echo "Clonazione repository pipeline-skeleton..."
                git clone https://github.com/acicfede/pipeline-skeleton.git "$TARGET_DIR"
              else
                echo "Repository già presente, skip clone"
              fi

              echo "BOOTSTRAP COMPLETATO"
          volumeMounts:
            - name: workbench-storage
              mountPath: /opt/app-root/src
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: nuovo-workbench
  namespace: ml
  labels:
    app: nuovo-workbench
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/image-display-name: "Jupyter | PyTorch LLM Compressor | CUDA | Python 3.12"
    notebooks.opendatahub.io/oauth-logout-url: "https://rhods-dashboard-redhat-ods-applications.apps.privateailab.acic.accenture/projects/ml?notebookLogout=nuovo-workbench"
    notebooks.opendatahub.io/last-image-selection: "jupyter-pytorch-llmcompressor:2025.2"
    opendatahub.io/hardware-profile-namespace: ml
    opendatahub.io/username: admin
    openshift.io/display-name: nuovo-workbench
spec:
  template:
    spec:
      serviceAccountName: ml-workbench
      enableServiceLinks: false
      containers:
        - name: nuovo-workbench
          image: image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/jupyter-pytorch-llmcompressor:2025.2
          imagePullPolicy: Always
          workingDir: /opt/app-root/src
          env:
            - name: NOTEBOOK_ARGS
              value: |
                --ServerApp.port=8888
                --ServerApp.token=''
                --ServerApp.password=''
                --ServerApp.base_url=/notebook/ml/nuovo-workbench
                --ServerApp.quit_button=False
          ports:
            - containerPort: 8888
              name: notebook-port
          resources:
            requests:
              cpu: "1"
              memory: 8Gi
            limits:
              cpu: "2"
              memory: 8Gi
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: workbench-storage
            - mountPath: /dev/shm
              name: shm
      volumes:
        - name: workbench-storage
          persistentVolumeClaim:
            claimName: nuovo-workbench-pvc
        - name: shm
          emptyDir:
            medium: Memory






