apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: run-kfp-yaml
spec:
  params:
    - name: pipeline-yaml-url
    - name: pipeline-name
    - name: kfp-endpoint
  steps:
    - name: upload-and-run
      image: quay.io/fedora/python-311
      script: |
        set -e

        echo "Installo curl..."
        if ! command -v curl; then
          dnf install -y curl || microdnf install -y curl
        fi

        echo "Scarico la pipeline..."
        curl -k -L "$(params.pipeline-yaml-url)" -o pipeline.yaml

        TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

        echo "Upload della pipeline a KFP..."
        curl -k -X POST "$(params.kfp-endpoint)/apis/v1beta1/pipelines/upload" \
          -H "Authorization: Bearer $TOKEN" \
          -F "uploadfile=@pipeline.yaml" \
          -F "name=$(params.pipeline-name)" \
          -o response.json

        echo "Risposta Upload:"
        cat response.json

        PIPELINE_ID=$(grep -o '"id": *"[^"]*"' response.json | head -1 | cut -d'"' -f4)

        echo "Pipeline ID: $PIPELINE_ID"

        echo "Avvio della pipeline..."
        curl -k -X POST "$(params.kfp-endpoint)/apis/v1beta1/runs" \
          -H "Authorization: Bearer $TOKEN" \
          -H "Content-Type: application/json" \
          -d "{
            \"name\": \"$(params.pipeline-name)-run\",
            \"pipeline_spec\": { \"pipeline_id\": \"$PIPELINE_ID\" }
          }"
